steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/cesapi:latest', '-f', './Dockerfile', '.']
options:
 machineType: 'N1_HIGHCPU_32'
images:
- 'us.gcr.io/$PROJECT_ID/cesapi:latest'
